server:
  port: 8081
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 30s

log:
  format: "json"
  level: info

env: local

postgres:
  primary:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "root"
    database: "ims_db"
    debug_mode: false
    prepare_stmt: false
    skip_default_transaction: false

  replicas: []

  pool:
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: 1h

redis:
  endpoint: "localhost:6379"
  db: 0
