postgres:
  master:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "root"
    dbname: "ims_db"
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: "30m"
    debug_mode: true
  slaves:
    - host: "slave1-host"
      port: "5432"
      username: "postgres"
      password: "yourpassword"
      dbname: "ims_db"
      max_open_conns: 10
      max_idle_conns: 5
      conn_max_lifetime: "30m"
      debug_mode: false
